### ISSUE TITLE
Question about layer_id

### ISSUE THREAD

**Issue by sorcererrandy** [andyzoujm/representation-engineering#10]
Hi! When I run your notebook, I wonder how can define layer_id for emotion control? 

Looking forward to hear your answers, thank you!

**Comment by justinphan3110** [comment]
Hi @sorcererrandy , layer_id and coeff are tuned parameters. In [emotion_concept.ipynb](https://github.com/andyzoujm/representation-engineering/blob/main/examples/primary_emotions/emotion_concept.ipynb) and [emotion_function.ipynb](https://github.com/andyzoujm/representation-engineering/blob/main/examples/primary_emotions/emotion_function.ipynb). We choose `layer_id = list(range(-11, -30, -1))` for 13B Llama2-chat and `list(range(-5, -18, -1))` for 7B Mistral/Llama2-chat

**Comment by sorcererrandy** [comment]
Thanks for your answer. I have a further question: how are the layer_id and coeff adjusted? Should I adjust the layer_id based on the accuracy after training the rep_reader, or should I adjust it based on the text output from the model?

**Comment by andyzoujm** [comment]
We usually use the set of layers that correspond to high reading accuracy, but feel free to also adjust it and coeff based on the output and your usecase.

**Comment by sorcererrandy** [comment]
I understand. Thanks!

**Comment by shiqichen17** [comment]
Hello! Could you please clarify the meaning of the "-" symbol in this context? I'm asking because I noticed its use in the code snippet from `honesty_control_TQA.ipynb`, there is:`layer_ids = np.arange(8, 32, 3)`.  Could you explain why there is a difference here?

**Comment by zhoushang2003** [comment]
@justinphan3110 How should I define the layer_id for 70B Llama2-chat in emotion_concept and emotion_function?

**Comment by shiqichen17** [comment]
I've received your e-mail , and I'll reply soon:)Shiqi Chen
