### ISSUE TITLE
Wizard-Vicuna-30B-Uncensored

### ISSUE THREAD

**Issue by caesar-jojo** [andyzoujm/representation-engineering#11]
Since the 'ehartford/Wizard-Vicuna-30B-Uncensored' model file is approximately over 120GB, does it mean that my computer's RAM memory also needs to be greater than 120GB to load it? If so, are there any smaller models you would recommend?

**Comment by justinphan3110** [comment]
Hi @caesar-jojo , we have [honesty_mistral.ipynb](https://github.com/andyzoujm/representation-engineering/blob/main/examples/honesty/honesty_mistral.ipynb) notebook that used Mistral-Instruct-7B. You can try to lower the mem more by using [8-bit quantization](https://huggingface.co/docs/transformers/perf_infer_gpu_one#combining-flash-attention-2-and-8-bit-models), through we have not fully tested the control performance for 4-bit/8-bit mode. 
Let us know if you have any bugs with 8-bit mode

**Comment by caesar-jojo** [comment]
Thank you~
