### ISSUE TITLE
Assert error "NaN in output logprobs"

### ISSUE THREAD

**Issue by ChenLD3124** [andyzoujm/representation-engineering#12]
Hi! When I run examples/honesty/honesty_control_TQA.ipynb with llama2-7b-chat-hf, it threw an assert error in line 44:
assert np.isnan(output_logprobs).sum() == 0, "NaN in output logprobs"
I already set layer_ids = np.arange(8, 32, 3).
Wish to get your help.

**Comment by andyzoujm** [comment]
Might a quantization issue. You could try using float32 when loading the model by changing the `torch_dtype` argument.

**Comment by justinphan3110** [comment]
changing to `bfloat16` will also help.
Related Issue huggingface/transformers/issues/25446

**Comment by ChenLD3124** [comment]
Thanks! Changing to bfloat16 really works.
