### ISSUE TITLE
I have some questions and ask the author for help

### ISSUE THREAD

**Issue by Chenjingxue** [andyzoujm/representation-engineering#13]
I would like to ask the author, in Step 1: Designing Stimulus and Task of LAT USER: <instruction> <experimental/reference prompt>
ASSISTANT: <output> Are the <instruction> and <output> of this template used as stimulus input, or are <instruction> used as input and <output> used as output? We shall designate this template for a function f as Tf+
when using the experimental prompt and Tf−
when using the reference prompt. What is the function f here? Could you please ask the author to help me answer my doubts? Thank you!

**Comment by andyzoujm** [comment]
"Function" here simply means some processes or behaviors of the model that you want to investigate. In the paper, one of the functions we examined was lying.
