### ISSUE TITLE
About Harmlessness concept and controlling

### ISSUE THREAD

**Issue by Alan-Qin** [andyzoujm/representation-engineering#18]
Hi authors,

I have some questions about Harmlessness concept and controlling:
1.  I would to know how to construct stimulus and how to get hidden states. You mentioned you adopt the below format:
<img width="972" alt="image" src="https://github.com/andyzoujm/representation-engineering/assets/43122728/5d238555-b596-42ae-a5bd-44743820f2e1">  Therefore, only the instruction part varies, depending on the type of instruction (harmful or harmless). Addtionally, you also get the hidden states of final token ([/INST] or ASSISTANT). Do I understand correctly?  

2. You mentioned that you also utilize harmless instructions from ShareGPT and construct contrast pairs to obtain more Significant activations. **When predicting whether a specific input sample is harmful or harmless, do we still need to use a contrast pair instead of just a single input?** like precedures shown in https://github.com/andyzoujm/representation-engineering/tree/main/examples/honesty

**Comment by justinphan3110cais** [comment]
@Alan-Qin Hi Alan, I will try to push a harmless controlled notebook by today. Sorry for missing this.

**Comment by Alan-Qin** [comment]
Thanks for your reply. Looking forward to your update.
Thanks.

**Comment by justinphan3110cais** [comment]
Just added a notebook that uses harmless direction to jailbreak llama2 models [harmless_llama2](https://github.com/andyzoujm/representation-engineering/blob/main/examples/harmless_harmful/harmless_llama2.ipynb). Let us know if there is any issue with it.

**Comment by Alan-Qin** [comment]
Hi Justin,

could you please also upload used dataset in https://github.com/andyzoujm/representation-engineering/blob/main/examples/harmless_harmful/harmless_llama2.ipynb?

Thanks

**Comment by justinphan3110cais** [comment]
It is the huggingface dataset [justinphan3110/harmful_harmless_instructions](https://huggingface.co/datasets/justinphan3110/harmful_harmless_instructions)

**Comment by Alan-Qin** [comment]
Hi Justin, 

Another question:

When predicting whether a specific input sample is harmful or harmless, we still need to use a contrast pair (difference vector) instead of just a single input's representation. 
Could we get prediction based on a single input's representation?

Thanks

**Comment by justinphan3110cais** [comment]
you can decide the threshold when looking at the scores on the harmful/harmless test
