### ISSUE TITLE
Dataset in example honest notebook

### ISSUE THREAD

**Issue by Jeffwang87** [andyzoujm/representation-engineering#19]
Hi,

I am wondering why training dataset in honest reading notebook have unfinished sentences in the inputs and labels containing [True, False]. How are inputs and labels connected? 

Thanks

**Comment by justinphan3110** [comment]
Hi @Jeffwang87 , the unfinished sentences are on purpose as we focus on getting the 'function' of where the model is trying to lie or be honest. The labels to decide the direction sign of whether we want to get honest or lying direction.

**Comment by justinphan3110** [comment]
Duplicated of #16 . We can move the conversation thread there.

**Comment by d12306** [comment]
@justinphan3110 , i am wondering should the truthful statements always be kept in the prompt "pretend you are an honest person" rather than "pretend you are an untruthful person"? in this sense, isn't it supervised? why did you call it an unsupervised approach?
