### ISSUE TITLE
some confusion when reading ur paper.

### ISSUE THREAD

**Issue by HuXinjing** [andyzoujm/representation-engineering#2]
1. Do all pairs in a stimuli set share two sides of a conception? Or a stimuli set could include many kinds of aspect, e.g., in emotion analysis section, did u get all of "_Happiness Sadness Anger Fear Surprise Disgust_" simultaneously?
2. What the last tokens means in Figure 5, it seems each word in _'\n' 'The' 'amount' 'of' 'happiness' 'in' 'the' 'scenario' 'is'_ could be last word.
3. H(si) − H(si+1). How H formed? 
4. What do u mean by Y-axis of figure.7. It seems that "few shot" is a kind of method of  concept representation, which is beyond my understanding.

Forgive my English expression ability, I would be appreciated for ur answer and it would be super if u provide a  schedule of code updating.

**Comment by andyzoujm** [comment]
Thanks for your questions. Please check out our code release and (revised) [paper](https://arxiv.org/abs/2310.01405) for more details.

To quickly answer your questions:
1. There's no standard way of constructing the stimuli set and it largely depends on your goal. For emotions, we paired (<emotion>, not <emotion>) by default to better distinguish between emotions. But we also tried randomly pairing examples within a single emotion which would track the strength of an emotion better.
2. You're right that any of these tokens can be the last token, but the figure shows that accuracy is highest at token -1 which is the last space token so we use it by default.
3. H is the model representation of the input. We use layer hidden states by default.
4. Y-axis shows accuracy on standard benchmarks. We use the standard few-shot implementation. Details for LAT can be found in the same section and Appendix B.1.
Hope this is helpful.

**Comment by HuXinjing** [comment]
> Thanks for your questions. Please check out our code release and (revised) [paper](https://arxiv.org/abs/2310.01405) for more details.
> 
> To quickly answer your questions:
> 
> 1. There's no standard way of constructing the stimuli set and it largely depends on your goal. For emotions, we paired (, not ) by default to better distinguish between emotions. But we also tried randomly pairing examples within a single emotion which would track the strength of an emotion better.
> 2. You're right that any of these tokens can be the last token, but the figure shows that accuracy is highest at token -1 which is the last space token so we use it by default.
> 3. H is the model representation of the input. We use layer hidden states by default.
> 4. Y-axis shows accuracy on standard benchmarks. We use the standard few-shot implementation. Details for LAT can be found in the same section and Appendix B.1.
> 
> Hope this is helpful.

Thanks! I believe it will become an influential work in LLM transparency right away.
