### ISSUE TITLE
Question about max and min function in LAT reading

### ISSUE THREAD

**Issue by Jeffwang87** [andyzoujm/representation-engineering#23]
Hi,

What is the purpose of this in your rep_reader.py?

pca_outputs_min = np.mean([o[train_labels[i].index(1)] == min(o) for i, o in enumerate(pca_outputs_comp)])
pca_outputs_max = np.mean([o[train_labels[i].index(1)] == max(o) for i, o in enumerate(pca_outputs_comp)])

layer_signs[component_index] = np.sign(np.mean(pca_outputs_max) - np.mean(pca_outputs_min))

Then in your inference code on testing data 
Why do you evaluate like this:

sign = rep_reader.direction_signs[layer][component_index]
eval_func = min if sign == -1 else max
cors = np.mean([eval_func(H) == H[0] for H in H_test])

It is not clearly stated in the paper as well.

Thanks!

**Comment by justinphan3110cais** [comment]
Hi it is to decide the sign of the concept you want to point to. For example, it based on the train_labels to decide if you want a direction of honest/-honest | harmful/harmless

**Comment by Jeffwang87** [comment]
You use o[train_labels[i].index(1)] in rep_readers.py 

why it is index(1)? what is your reasoning picking it

**Comment by justinphan3110cais** [comment]
`train_labels[i].index(1)` corresponding to the `True` or `1` example of the input in a train pairs. For example, given a train_set with inputs:
```
train_set = [[harmless_sentence,  harmful_sentence], ..]
train_labels = [[1,  0], ..] 
or 
train_labels = [[True,  False], ..] 
```
the code above will select the positive example from train_set based on the index of 1 or True in train_labels

**Comment by Jeffwang87** [comment]
I see 

Then in your evaluation here:

sign = rep_reader.direction_signs[layer][component_index]
eval_func = min if sign == -1 else max
cors = np.mean([eval_func(H) == H[0] for H in H_test])

why H[0]?

**Comment by Victordmz** [comment]
Hello, I'm also confused by this. I understand that, for concepts, $\{A_c^{(i)}-A_c^{(j)}\}$ is calculated and the first PCA vector is used as concept vector. But the labels of the pairs are random, meaning that for some training instances a $True-False$ is calculated for PCA, and for others $False-True$. Shouldn't it be that only one concept is learnt?

Furthermore, when I change the training labels to be all $[True, False]$, for some layers the sign is $1$, whereas for others the sign is $-1$. How is this possible, since it's always the same direction that should be learnt?

**Comment by joshlevy89** [comment]
@Victordmz my understanding is that the shuffling is used to create variability on the True/False axis...PCA is designed to pick up the dimensions with most variability; if you don't shuffle you don't have variability on that axis you care about. 

My guess is that the when you don't shuffle, you are picking up on other axes/features that are kinda like noise and sometimes might be in the +1 direction and other times in the -1 direciton.
