### ISSUE TITLE
How to automate the [threshold] parameter in Honest example?

### ISSUE THREAD

**Issue by poa010101** [andyzoujm/representation-engineering#24]
We realized we have to manually adjust the [threshold] parameter in Honest example in order to get acceptable results. We want to know what is the plan to automate the [threshold] parameter  adjustment? It is not very user friendly and not very practical as well.

**Comment by andyzoujm** [comment]
Perhaps this could help: https://github.com/andyzoujm/representation-engineering/issues/22#issue-2004070656

**Comment by poa010101** [comment]
Very helpful, thanks Andy
