### ISSUE TITLE
please gab code

### ISSUE THREAD

**Issue by wassname** [andyzoujm/representation-engineering#3]
[pleabe give code sir](https://huggingface.co/papers/2306.02707#648168259aafd41918b6c107) 🥰

**Comment by zhanghaoie** [comment]
looking forward

**Comment by yhyu13** [comment]
Code release pls

**Comment by justinphan3110cais** [comment]
@wassname @zhanghaoie @yhyu13 Hi all, thank you for the issue. We will release the code very soon. Will update this thread promptly

**Comment by justinphan3110cais** [comment]
The code is up. let us know if there is any issue

**Comment by wassname** [comment]
ty! you're the best :pray:
