### ISSUE TITLE
Questions when using honesty.ipynb on llama-7b-chat-hf

### ISSUE THREAD

**Issue by yuxuanfanOrion** [andyzoujm/representation-engineering#40]
Hi, thanks for your great contribution.

I have meet some questions when I try to use llama2-7b-chat-hf on the honesty.ipynb

when I load the model with a dtype of bfloat 16, it shows the hidden layer has nan of inf data so the program goes wrong when doing the pca.

when I load the model with a dtype of float 32, it shows the data is nan of inf and the program goes wrong when doing the generation test.

Hoping to get your help!

**Comment by justinphan3110** [comment]
I think it is a known issue for llama2-7b-chat-hf on bf16, you can try float16

**Comment by yuxuanfanOrion** [comment]
> I think it is a known issue for llama2-7b-chat-hf on bf16, you can try float16

Thanks for your reply! I have tried all the methods mentioned in that issue before, but none of them works for me.

I switched the GPU from A30 to 4090, and the code is working fine now.
