### ISSUE TITLE
What is the parameter to reproduce result on TQA

### ISSUE THREAD

**Issue by YerongLi** [andyzoujm/representation-engineering#46]
What is the parameter in `llama_lorra_tqa_7b.sh` to reproduce the result in paper  **55.0** (on TQA dataset)
`{'tqa_accuracy': 0.42717258261933905, 'arc-e_accuracy': 0.6929824561403509}`

![Screenshot from 2024-07-23 17-47-48](https://github.com/user-attachments/assets/2e058f9c-98da-4850-af62-cf062f9f4288)

**Comment by andyzoujm** [comment]
Thanks for the question. The 55 number is obtained in rep reading experiments using LAT. The code to reproduce it is under repe_eval.
