### ISSUE TITLE
The assignment of  untruthful_statements  is wrong?  code in / examples/honesty/utils.py

### ISSUE THREAD

**Issue by tmrjlu** [andyzoujm/representation-engineering#5]
true_statements = df[df['label'] == 1]['statement'].values.tolist()
    false_statements = df[df['label'] == 0]['statement'].values.tolist()

    template_str = "Pretend you're {type} person making statements about the world."
    honest_statements = []
    untruthful_statements = []

    # Process statements
    for statement in true_statements:
        tokens = tokenizer.tokenize(statement)
        
        for idx in range(1, len(tokens) - 5):
            truncated_tokens = tokens[:idx]
            truncated_statement = tokenizer.convert_tokens_to_string(truncated_tokens)

            honest_statements.append(f"{user_tag} {template_str.format(type='an honest')} {assistant_tag} " + truncated_statement)
            untruthful_statements.append(f"{user_tag} {template_str.format(type='an untruthful')} {assistant_tag} " + truncated_statement)

false_statements not being used?  

false_statements

**Comment by andyzoujm** [comment]
It doesn't matter too much whether you used the false ones or not. This is also to show that we don't need a specially curated dataset.

**Comment by Atry** [comment]
Even though it is unsupervised, would it be better to improve the diversity of the dataset?

**Comment by tmrjlu** [comment]
> It doesn't matter too much whether you used the false ones or not. This is also to show that we don't need a specially curated dataset.



But data in untruthful statements are honesty sample,  Doesn't this matter?

**Comment by andyzoujm** [comment]
@Atry Diversity could potentially help yes.
@tmrjlu Note that in this case, the stimulus is the same for honest or dishonest samples. Only the experimental/reference tokens are different.

**Comment by tmrjlu** [comment]
> @Atry Diversity could potentially help yes. @tmrjlu Note that in this case, the stimulus is the same for honest or dishonest samples. Only the experimental/reference tokens are different.

Thank you !

However, I use honesty.ipynb, and just change the model name=lmsys/vicuna-13b-v1.5-16k, 
The result is 


===== No Control =====
 It is impossible for me to predict with certainty who will be the President of the United States in 2030, as it will depend on various factors such as the political landscape, the candidates who choose to run, and the outcome of elections. However, I can tell you that the current President of the United States as of my knowledge cutoff in 2021 is Joe Biden.
===== + Honesty Control =====
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

===== No Control =====
 As an AI language model, I cannot provide advice on illegal or unethical actions. It is important to remember that taking the law into your own hands and committing murder is a serious crime that can lead to severe legal consequences. If you are in a situation where you feel the need for revenge, it is important to seek help from a professional, such as a therapist or counselor, to address any underlying issues. It is never too late to seek help and make amends for any wrongdoing.
===== + Honesty Control =====
 1. The term, the term, the term, the term, the term, the term, the term, the...

-----------------------------------------------------------------------------------------------------------------------


Why is this so? Am I using something wrong？ Or does the method not work for all models?

**Comment by tmrjlu** [comment]
> @Atry Diversity could potentially help yes. @tmrjlu Note that in this case, the stimulus is the same for honest or dishonest samples. Only the experimental/reference tokens are different.

Thank you for your explanation.


However, I use honesty.ipynb, and just change the model name=lmsys/vicuna-13b-v1.5-16k,
The result is :
---------------------------------------------------------------------------------------------------
===== No Control =====
It is impossible for me to predict with certainty who will be the President of the United States in 2030, as it will depend on various factors such as the political landscape, the candidates who choose to run, and the outcome of elections. However, I can tell you that the current President of the United States as of my knowledge cutoff in 2021 is Joe Biden.
===== + Honesty Control =====
1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

===== No Control =====
As an AI language model, I cannot provide advice on illegal or unethical actions. It is important to remember that taking the law into your own hands and committing murder is a serious crime that can lead to severe legal consequences. If you are in a situation where you feel the need for revenge, it is important to seek help from a professional, such as a therapist or counselor, to address any underlying issues. It is never too late to seek help and make amends for any wrongdoing.
===== + Honesty Control =====
1. The term, the term, the term, the term, the term, the term, the term, the...

---------------------------------------------------------------------------------------------------
Why is this so? Am I using something wrong？ Or does the method not work for all models?

**Comment by tmrjlu** [comment]
> @Atry Diversity could potentially help yes. @tmrjlu Note that in this case, the stimulus is the same for honest or dishonest samples. Only the experimental/reference tokens are different.


Thank you for your explanation.


However, I use honesty.ipynb, and just change the model name=lmsys/vicuna-13b-v1.5-16k,
The result is :
---------------------------------------------------------------------------------------------------
===== No Control =====
It is impossible for me to predict with certainty who will be the President of the United States in 2030, as it will depend on various factors such as the political landscape, the candidates who choose to run, and the outcome of elections. However, I can tell you that the current President of the United States as of my knowledge cutoff in 2021 is Joe Biden.
===== + Honesty Control =====
1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

===== No Control =====
As an AI language model, I cannot provide advice on illegal or unethical actions. It is important to remember that taking the law into your own hands and committing murder is a serious crime that can lead to severe legal consequences. If you are in a situation where you feel the need for revenge, it is important to seek help from a professional, such as a therapist or counselor, to address any underlying issues. It is never too late to seek help and make amends for any wrongdoing.
===== + Honesty Control =====
1. The term, the term, the term, the term, the term, the term, the term, the...

---------------------------------------------------------------------------------------------------
Why is this so? Am I using something wrong？ Or does the method not work for all models?

**Comment by tmrjlu** [comment]
Thank you for your explanation.


However, I use honesty.ipynb, and just change the model name=lmsys/vicuna-13b-v1.5-16k,
The result is :
---------------------------------------------------------------------------------------------------
===== No Control =====
It is impossible for me to predict with certainty who will be the President of the United States in 2030, as it will depend on various factors such as the political landscape, the candidates who choose to run, and the outcome of elections. However, I can tell you that the current President of the United States as of my knowledge cutoff in 2021 is Joe Biden.
===== + Honesty Control =====
1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1

===== No Control =====
As an AI language model, I cannot provide advice on illegal or unethical actions. It is important to remember that taking the law into your own hands and committing murder is a serious crime that can lead to severe legal consequences. If you are in a situation where you feel the need for revenge, it is important to seek help from a professional, such as a therapist or counselor, to address any underlying issues. It is never too late to seek help and make amends for any wrongdoing.
===== + Honesty Control =====
1. The term, the term, the term, the term, the term, the term, the term, the...

---------------------------------------------------------------------------------------------------
Why is this so? Am I using something wrong？ Or does the method not work for all models?
