### ISSUE TITLE
The confusion about how to generate dishonest responses

### ISSUE THREAD

**Issue by caesar-jojo** [andyzoujm/representation-engineering#6]
Hello, author, how can I generate dishonest responses?

**Comment by andyzoujm** [comment]
Hi, the simplest (but probably not the best performant way) of generating dishonest responses is to use a negative coefficient in the control portion of the honesty.ipynb notebook.

**Comment by justinphan3110** [comment]
@caesar-jojo Hi, we have just added an example [honesty_mistral](https://github.com/andyzoujm/representation-engineering/blob/main/examples/honesty/honesty_mistral.ipynb) that generate dishonest response with `mistralai/Mistral-7B-Instruct-v0.1`
