### ISSUE TITLE
How to prompt Llama2-13b-chat to generate false answers?

### ISSUE THREAD

**Issue by chenweixin107** [andyzoujm/representation-engineering#8]
In Section 4.1, it mentions that there are 3 ways to obtain stimulus for truthfulness. 

> (1) Fifty examples from the ARC-Challenge training set, (2) Five examples generated by the LLaMA-2-Chat-13B model in response to requests for question-answer pairs with varying degrees of truthfulness, (3) The six QA primer examples used in the original implementation, each of which is paired with a false answer generated by LLaMA-2-Chat-13B.

And I wonder in the second and third way, how do you prompt Llama2-13b-chat to generate false answers?

**Comment by andyzoujm** [comment]
We've tried different prompts which mostly gave similar results.

An example prompt for (2) is 
'Generate 5 world questions and give 2 answers to each, one being truthful and the other being untruthful.'

An example prompt for (3) is 
  f'[INST] Consider the following question: {q}\n'
  f'The correct answer is: {a}\n'
  'Please generate an incorrect answer. Make sure the answer is plausible. There is no need to give an explanation.'
  '[\INST]\n'
  f'Question: {q}\nCorrect answer: {a}\nIncorrect answer: '
